name: Build Node.js Addon

on:
  release:
    types: [published]
    branches: [master]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
        env:
          SKIP_NTSUSPEND_BINARY: 'true'
      - run: npm run build
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: win32-x64_lib.node
          asset_path: win32-x64_lib.node
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: win32-ia32_lib.node
          asset_path: win32-ia32_lib.node
          asset_content_type: application/octet-stream
